// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXLjJ3U8T-wDtTMXbNmK6BYTyIG31NqLI',
    appId: '1:579494933348:web:4be5c41358647375c54071',
    messagingSenderId: '579494933348',
    projectId: 'fir-auth-app-9ac94',
    authDomain: 'fir-auth-app-9ac94.firebaseapp.com',
    storageBucket: 'fir-auth-app-9ac94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCW2q6VkczcCccYjUbFObwUIfZ1Pdl-A',
    appId: '1:579494933348:android:5a933485bc01f0bcc54071',
    messagingSenderId: '579494933348',
    projectId: 'fir-auth-app-9ac94',
    storageBucket: 'fir-auth-app-9ac94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo7GoXVhw6hBQMRQqsQ7hLRSPjLfyrgIM',
    appId: '1:579494933348:ios:25bcc383a9db10f1c54071',
    messagingSenderId: '579494933348',
    projectId: 'fir-auth-app-9ac94',
    storageBucket: 'fir-auth-app-9ac94.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo7GoXVhw6hBQMRQqsQ7hLRSPjLfyrgIM',
    appId: '1:579494933348:ios:c49252c1b1001d05c54071',
    messagingSenderId: '579494933348',
    projectId: 'fir-auth-app-9ac94',
    storageBucket: 'fir-auth-app-9ac94.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
